### ISSUE TITLE
Constant error since a few days ago.

### ISSUE THREAD

**Issue by Agalondia** [genshade/genshade.github.io#1]
Is it just me or does anyone experience this weird error after playing for a minute since a few days ago?
![GenshinImpact 2021-12-09 21-07-24](https://user-images.githubusercontent.com/17707429/145557053-40af5fed-cb43-4c90-8119-4f99b4ad46ef.jpg)
 
It doesn't happen on the normal game, so i don't know what's wrong.

**Comment by genshade** [comment]
It's working fine for me. Do you play co-op? Maybe it has something to do with the error.

**Comment by Agalondia** [comment]
oh yeah, do you use effects that access the depth buffer? use display depth for a while and see if you get the error.

**Comment by genshade** [comment]
I just tested. No errors whatsoever.

**Comment by Agalondia** [comment]
> I just tested. No errors whatsoever.

Nevermind, it's my VPN messing things up, the game works fine without it.
